### PR TITLE
Added italian language

### PR DESCRIPTION
**Pull request by rocco27**

### CODE REVIEW

**Comment by own3mall** [comment]
Thanks, this isn't the exact code that is run though, but I will try to update the main script with these changes soon.  When I'm done, I'll merge this one.  :)

**Comment by rocco27** [comment]
Yea I know. Thanks.

**Comment by own3mall** [comment]
Added into the main script.  Thanks!

**Comment by own3mall** [comment]
It didn't work... need to figure out a way to support adding languages... the script works by diffing what is currently there.  I'll see what I can do when I get more time.

**Comment by rocco27** [comment]
Okey.

**Comment by Zorrototo** [comment]
Maybe simply add a copy of the english files in a Italian folder for all the resources (website, modules) here at GitHub??

**Comment by own3mall** [comment]
See if it's good now.  I added new code which hasn't been committed here (nor will it probably be just cause I'm lazy)...

It looks at the English folder, compiles a list of files that are there after pulling, copies the new language files, checks to see if the files from the English folder exist in the new language folder (for example, Italian), and if that file exists with the same name, it is added to github.  :)

In case something happens to me, I'll probably put the full script including passwords on GitLab at some point @Zorrototo (Our private Git hosting)

**Pull request closed without merging**
